 .\build\bin\Release\sd.exe -m C:\Users\dsx19\.cache\huggingface\hub\models--stabilityai--stable-diffusion-3-medium\blobs\69a950c5d143ce782a7423c532c8a12b75da6a37b0e6f26a322acf4e76208912 --cfg-scale 5 --steps 30 --sampling-method euler  -H 1024 -W 1024 --seed 42 -p "fantasy medieval village world inside a glass sphere , high detail, fantasy, realistic, light effect, hyper detail, volumetric lighting, cinematic, macro, depth of field, blur, red light and clouds from the back, highly detailed epic cinematic concept art cg render made in maya, blender and photoshop, octane render, excellent composition, dynamic dramatic cinematic lighting, aesthetic, very inspirational, world inside a glass sphere by james gurney by artgerm with james jean, joe fenton and tristan eaton by ross tran, fine details, 4k resolution"


.\build\bin\Release\sd.exe -m C:\Users\dsx19\.cache\huggingface\hub\models--stabilityai--stable-diffusion-3-medium\blobs\69a950c5d143ce782a7423c532c8a12b75da6a37b0e6f26a322acf4e76208912 --cfg-scale 5 --steps 30 --sampling-method euler -H 1024 -W 1024 --seed 42 -p "Dreamlike floating islands suspended in an infinite galaxy, each island covered in lush gardens and flowing waterfalls, surrounded by enormous ethereal butterflies radiating neon blues and pinks, cosmic dust swirling gently around. The scene is illuminated by a mix of starlight and the soft glow from the butterflies’ wings, creating an enchanting fantasy world."

.\build\bin\Release\sd.exe -m C:\Users\dsx19\.cache\huggingface\hub\models--stabilityai--stable-diffusion-3-medium\blobs\69a950c5d143ce782a7423c532c8a12b75da6a37b0e6f26a322acf4e76208912 --cfg-scale 5 --steps 30 --sampling-method euler -H 1024 -W 1024 --seed 42 -p "A vibrant, timeless carnival set on fluffy, sunlit clouds above an endless ocean. Brightly colored tents, Ferris wheels, and carousel animals float as if weightless, with wisps of cloud mingling through each ride, illuminated by a mix of carnival lights casting warm glows."

.\build\bin\Release\sd.exe -m C:\Users\dsx19\.cache\huggingface\hub\models--stabilityai--stable-diffusion-3-medium\blobs\69a950c5d143ce782a7423c532c8a12b75da6a37b0e6f26a322acf4e76208912 --cfg-scale 5 --steps 30 --sampling-method euler -H 1024 -W 1024 --seed 42 -p "A futuristic, overgrown garden where flowers emit neon lights in shades of violet and aqua, blooming from trees made of metal and wires. Robotic butterflies flit between the plants, and in the background, abandoned skyscrapers slowly crumble into the landscape."

.\build\bin\Release\sd.exe -m C:\Users\dsx19\.cache\huggingface\hub\models--stabilityai--stable-diffusion-3-medium\blobs\69a950c5d143ce782a7423c532c8a12b75da6a37b0e6f26a322acf4e76208912 --cfg-scale 5 --steps 30 --sampling-method euler -H 1024 -W 1024 --seed 42 -p "Ancient stone temple ruins overtaken by gigantic, bioluminescent mushrooms glowing in rich greens and purples, casting an otherworldly light on the moss-covered stones, with ethereal fog swirling around the roots."

.\build\bin\Release\sd.exe -m C:\Users\dsx19\.cache\huggingface\hub\models--stabilityai--stable-diffusion-3-medium\blobs\69a950c5d143ce782a7423c532c8a12b75da6a37b0e6f26a322acf4e76208912 --cfg-scale 5 --steps 30 --sampling-method euler -H 1024 -W 1024 --seed 42 -p "A forest existing across dimensions, where trees have shimmering, translucent bark, and from their roots grow crystals of varying colors and intensities. Strange, ethereal creatures dart between trees, and the sky above shimmers in shifting hues."

.\build\bin\Release\sd.exe -m C:\Users\dsx19\.cache\huggingface\hub\models--stabilityai--stable-diffusion-3-medium\blobs\69a950c5d143ce782a7423c532c8a12b75da6a37b0e6f26a322acf4e76208912 --cfg-scale 5 --steps 30 --sampling-method euler -H 1024 -W 1024 --seed 42 -p "A bustling, medieval-style city built on the scales of a colossal dragon sleeping in a vast valley, with stone bridges arching across its wings, and soft sunlight pouring through mountain peaks in the background."



"Dreamlike floating islands suspended in an infinite galaxy, each island covered in lush gardens and flowing waterfalls, surrounded by enormous ethereal butterflies radiating neon blues and pinks, cosmic dust swirling gently around. The scene is illuminated by a mix of starlight and the soft glow from the butterflies’ wings, creating an enchanting fantasy world, hyper-detailed, volumetric light, surreal, with an otherworldly calm, 4k resolution."

"A vibrant, timeless carnival set on fluffy, sunlit clouds above an endless ocean. Brightly colored tents, Ferris wheels, and carousel animals float as if weightless, with wisps of cloud mingling through each ride. Carnival lights cast warm glows over the cloudy landscape, and children’s laughter seems to echo from unseen spaces. Light beams and lens flares create a nostalgic, magical ambiance, with tiny, whimsical details in every corner, 4k resolution, hyper-detailed, cinematic depth."